Makefile
kinto_updater/__init__.py
kinto_updater/tests/test_updater.py

Remove a lot of features that were present in here in order to have them
instead provided in the Kinto.py project.
r? @natim

Migrate to Kinto.py 1.0.

---

README.rst

Rename to "kinto-signer".

---

.gitignore
.travis.yml
kinto_signer/__init__.py
kinto_signer/generate_keypair.py
kinto_signer/hasher.py
kinto_signer/signer.py
kinto_signer/tests/test_signer.py
kinto_signer/updater.py
tox.ini

Port kinto-signer to Python3.

---

kinto_signer/signer.py

Handle bytes and unicode string for signer payload and verifier.

---

kinto_signer/tests/test_updater.py
kinto_signer/updater.py

Related bug in Kinto/kinto#433.

Make sure we can sync on an empty remote collection.

---

kinto_signer/hook.py
kinto_signer/tests/functional.py
kinto_signer/tests/test_updater.py
kinto_signer/updater.py

Handle destination creation with public permissions on collection.

---

kinto_signer/tests/functional.py
kinto_signer/tests/test_updater.py
kinto_signer/updater.py

Set the source status after a succesful signature.

---

kinto_signer/hook.py
kinto_signer/tests/test_utils.py
kinto_signer/utils.py

Move the parse_resource utility to a utils module

---

kinto_signer/hook.py
kinto_signer/signer/autograph.py
kinto_signer/signer/local_ecdsa.py
kinto_signer/tests/config/signer.ini
kinto_signer/tests/test_signer.py

Fixes #5 
r? @Natim @leplatrem

Update signatures to embed metadata.

---

README.rst
kinto_signer/__init__.py
kinto_signer/hook.py
kinto_signer/signer/autograph.py
kinto_signer/signer/local_ecdsa.py
kinto_signer/tests/config/signer.ini
kinto_signer/tests/functional.py
kinto_signer/tests/test_signer.py

It is done accordingly in other plugins.
r? @Natim @leplatrem

Replace kinto_signer by kinto.signer in settings.

---

CHANGELOG.rst
Makefile
requirements.txt
setup.py

Waiting for #39 to be merged first, and then I will be able to release.

Prepare 0.1.0

---

.travis.yml
Makefile
dev-requirements.txt
kinto_signer/tests/test_serializer.py
tox.ini

Test deeply nested data structures with canonical_json (fixes #26)

---

kinto_signer/tests/test_updater.py

Use mock.patch.object in the tests.

---

kinto_signer/signer/autograph.py
kinto_signer/tests/test_signer.py

Use the new autograph APIs.

---

CHANGELOG.rst
setup.py

Preparing release 0.2.0

---

CHANGELOG.rst
kinto_signer/hook.py
kinto_signer/signer/__init__.py
kinto_signer/signer/autograph.py
kinto_signer/signer/base.py
kinto_signer/signer/local_ecdsa.py
kinto_signer/tests/test_plugin_setup.py
kinto_signer/tests/test_signer.py

Add signer entry in heartbeat view (fixes #50)

---

kinto_signer/tests/test_serializer.py

Add more tests for serializers

---

kinto_signer/__init__.py
kinto_signer/tests/test_plugin_setup.py

Change the format of exposed settings in the capability (fixes #63)

---

README.rst
kinto_signer/__init__.py
kinto_signer/tests/config/signer.ini
kinto_signer/tests/test_utils.py
kinto_signer/utils.py

Change settings format (fixes #35)

---

CHANGELOG.rst
README.rst
kinto_signer/signer/__init__.py
kinto_signer/signer/autograph.py
kinto_signer/signer/base.py
kinto_signer/signer/local_ecdsa.py
kinto_signer/tests/functional.py
kinto_signer/tests/test_plugin_setup.py
kinto_signer/tests/test_signer.py

Changes had to made to kinto-signer in order to get it work with the verifier in PSM
/cc @mozmark and @franziskuskiefer 
r? @Natim

Use Content-Signature protocol from Autograph

---

CHANGELOG.rst
MANIFEST.in
setup.py

Prepare 0.3

---

README.rst
kinto_signer/updater.py

Add mention about destination collection permissions (ref #55)

---

CHANGELOG.rst
kinto_signer/__init__.py
kinto_signer/tests/test_plugin_setup.py

Return 503 instead of 500 when signing fails (fixes #71)

---

CHANGELOG.rst
setup.py

Prepare 0.4.0

---

README.rst
demo/canonicaljson.js
demo/index.html
demo/index.js
demo/webcrypto.js
demo/x509ecdsa.js

Add example of Javascript signature validation

---

kinto_signer/__init__.py
kinto_signer/tests/functional.py
kinto_signer/tests/test_plugin_setup.py
kinto_signer/tests/test_updater.py
kinto_signer/updater.py

Rename remote into destination.

---

CHANGELOG.rst
setup.py

Prepare 0.5.0

---

CHANGELOG.rst
kinto_signer/__init__.py
kinto_signer/tests/__init__.py
kinto_signer/tests/test_updater.py
kinto_signer/updater.py

This updates kinto-signer according to the changes made in https://github.com/Kinto/kinto/releases/tag/3.0.0.

Update to kinto.core

---

scripts/validate_signature.py

Validate the kinto.stage signature .
r? @tarekziade

Add a script to make sure the collection signature is valid.

---

.travis.yml
CHANGELOG.rst
README.rst
demo/index.js
kinto_signer/serializer.py
kinto_signer/tests/functional.py
kinto_signer/tests/test_serializer.py
kinto_signer/tests/test_updater.py
kinto_signer/updater.py
scripts/e2e.py
scripts/validate_signature.py

Ref https://github.com/Kinto/kinto/issues/687

Add timestamp prior to signing

---

CHANGELOG.rst
kinto_signer/tests/test_utils.py
kinto_signer/utils.py

Raise configuration errors if resources are not configured correctly (ref #88)

---

CHANGELOG.rst
setup.py

Preparing release 0.7.0

---

CHANGELOG.rst
kinto_signer/tests/test_updater.py
kinto_signer/updater.py

Make sure the timestamp is updated.

---

CHANGELOG.rst
kinto_signer/__init__.py
kinto_signer/tests/test_plugin_setup.py

Prevents crash with events on default bucket on Kinto < 3.3

---

CHANGELOG.rst
setup.py

Preparing release 0.7.1

---

CHANGELOG.rst
kinto_signer/tests/test_events.py
kinto_signer/updater.py

Provide the old value on destination records updates (fixes #104)

---

CHANGELOG.rst
kinto_signer/tests/test_events.py
kinto_signer/updater.py

Set specific user_id in events

---

CHANGELOG.rst
kinto_signer/__init__.py
kinto_signer/tests/test_plugin_setup.py

Refs https://github.com/Kinto/kinto/issues/591
r? @tarekziade

Add kinto-signer plugin version in the capability.

---

CHANGELOG.rst
README.rst
scripts/e2e.py
scripts/validate_signature.py
setup.py

Prepare 0.7.3

---

CHANGELOG.rst
kinto_signer/__init__.py
kinto_signer/tests/config/signer.ini
kinto_signer/tests/test_plugin_setup.py

~~False alert, no problem found.
No entry added to changelog, just a test.~~ Found a crash with POST on `/buckets/cid/collections`
Fixes #116

Add test for batch signature requests

---

tests/functional.py

Make sure deleted are present.

---

kinto_signer/updater.py
tests/functional.py
tests/test_updater.py

Make sure that the signature is valid when all records have been deleted

---

CHANGELOG.rst
kinto_signer/updater.py
tests/test_updater.py
tox.ini

Warn in case the storage backend timezone is not correctly configured.

---

CHANGELOG.rst
setup.py

Preparing release 0.8.1

---

CHANGELOG.rst
dev-requirements.txt
kinto_signer/__init__.py
tests/test_plugin_setup.py

Add StatsD timer kinto.listeners.signer

---

CHANGELOG.rst
setup.py

Preparing release 0.9.0

---

scripts/e2e.py

This PR adds the necessary steps for an end-to-end test when the review/workflow is enabled.
It should continue to work with previous versions of kinto-signer.
**Highlights**
* now shows some information about server / config / parameters used
* use destination bucket/collection from server capabilities
* now fails properly if the signer plugin is not enabled
* now fails if the specified collection is not configured to be signed
* now requires `kinto-http.py >=7` to create editors/reviewers groups if group check is enabled
**Examples**
Example of run when no preview collection is configured:
```
$ python scripts/e2e.py --editor-auth=toto:tata                                     
Server: http://localhost:8888/v1
Author: basicauth:ee4f91385a660a64587375772f9888ba9d98d7ae791f81a68ecc92a51b208 …
```

Add workflow in e2e script

---

CHANGELOG.rst
README.rst
kinto_signer/listeners.py
scripts/e2e.py
tests/test_signoff_flow.py

Fixes #131
@tarekziade  | @Natim  r?

Do not check editor != reviewer if to review not enabled (fixes #131)

---

scripts/e2e.py

Fix perm fail in e2e when bucket already exists

---

CHANGELOG.rst
kinto_signer/__init__.py
tests/test_plugin_setup.py

Fix decoration of listener when StatsD is enabled (fixes #138)

---

CHANGELOG.rst
kinto_signer/listeners.py
kinto_signer/utils.py
tests/test_signoff_flow.py

Make sure that collection editor can retrigger a signature (fixes #136)

---

CHANGELOG.rst
requirements.txt
setup.py

Preparing release 0.9.2

---

CHANGELOG.rst
README.rst
kinto_signer/__init__.py
kinto_signer/listeners.py
tests/test_plugin_setup.py
tests/test_signoff_flow.py

Settings specific by bucket/collection (fixes #145)

---

README.rst
kinto_signer/__init__.py
tests/test_plugin_setup.py
tests/test_signoff_flow.py

Workflow settings name consistency (fixes #149)

---

README.rst
kinto_signer/__init__.py
kinto_signer/events.py
kinto_signer/listeners.py
tests/test_events.py

Send custom events on review request (fixes #157)

---

CHANGELOG.rst
kinto_signer/listeners.py
kinto_signer/updater.py
tests/test_signoff_flow.py
tests/test_updater.py

Copy kinto-admin UI fields to destination (fixes #161)

---

scripts/validate_signature.py

This is the same as #165, except for a different script that I missed the first time around.

validate_signature: This time for sure

---

.travis.yml
CHANGELOG.rst
Makefile
kinto_signer/__init__.py
kinto_signer/listeners.py
kinto_signer/updater.py
tests/config/signer-master.ini
tests/config/signer.ini
tests/functional.py
tests/test_events.py
tox.ini

Fixed inconsistencies with ResourceChanged (fixes #169)

---

CHANGELOG.rst
kinto_signer/serializer.py
tests/test_serializer.py

Add canonical_json iterators supports

---

Makefile
kinto_signer/updater.py
setup.py
tests/test_updater.py

After signing the collection, invalidate related paths.

---

scripts/README.rst
scripts/canonical_json.py

A CLI tool to be able get a canonical version of a JSON file to be able to create nice diffs between two versions.

Add a canonical JSON cli tool.

---

CHANGELOG.rst
kinto_signer/updater.py
setup.py
tests/test_updater.py

Log cache invalidation errors.

Cache invalidation

---

CHANGELOG.rst
kinto_signer/listeners.py
setup.py
tests/test_plugin_setup.py

Allow kinto-signer to update kinto-attachment metadata.

---

kinto_signer/updater.py
tests/test_updater.py

Remove additional / from collection_paths. Fixes #193

---

CHANGELOG.rst
kinto_signer/updater.py
tests/test_updater.py

Revamp of #198 with @leplatrem review.
If you think this is better let's merge it and close #198 or the other way around.

Invalidate all cache endpoints.

---

CHANGELOG.rst
kinto_signer/updater.py
tests/test_updater.py

Fix BadSignature error on empty collections.

---

CHANGELOG.rst
kinto_signer/__init__.py
kinto_signer/signer/autograph.py
kinto_signer/signer/local_ecdsa.py
kinto_signer/utils.py
tests/test_plugin_setup.py

Load settings default values (fixes #151)

---

CHANGELOG.rst
kinto_signer/updater.py
tests/test_signoff_flow.py

Fix permissions of automatically created preview/destination bucket (Fixes #155)

---

CHANGELOG.rst
README.rst
kinto_signer/__init__.py
kinto_signer/listeners.py
kinto_signer/utils.py
tests/config/signer.ini
tests/functional.py
tests/test_plugin_setup.py
tests/test_signoff_flow.py
tests/test_utils.py

Configure per bucket (fixes #144)

---

kinto_signer/utils.py
tests/test_utils.py

Add safety checks in configuration (fixes #216)

---

kinto_signer/__init__.py
tests/test_plugin_setup.py

Raise human friendly error on unknown group placeholder (Ref #211)

---

README.rst
kinto_signer/__init__.py
kinto_signer/listeners.py
kinto_signer/utils.py
tests/test_signoff_flow.py

Fix overriding of per-bucket signers (ref #215)

---

CHANGELOG.rst
kinto_signer/listeners.py
kinto_signer/updater.py
tests/test_plugin_setup.py
tests/test_signoff_flow.py

Initialize preview and destination with signature (fixes #226)

---

CHANGELOG.rst
kinto_signer/listeners.py
tests/test_signoff_flow.py

User does not have to be in the *reviewers* group to refresh a signature (fixes #233)

---

kinto_signer/updater.py

Log info on invalidation request (Fixes #238)

---

CHANGELOG.rst
README.rst
kinto_signer/__init__.py
kinto_signer/listeners.py
tests/test_plugin_setup.py
tests/test_signoff_flow.py

Deprecate separation of bucket/collection with . in settings (fixes #224)

---

CHANGELOG.rst
kinto_signer/listeners.py
tests/test_signoff_flow.py

The preview collection signature is now refreshed along the destination (fixes #236)

---

CHANGELOG.rst
README.rst
kinto_signer/listeners.py
kinto_signer/updater.py
tests/functional.py
tests/test_events.py
tests/test_signoff_flow.py
tests/test_updater.py

Add new tracking fields (fixes #137)

---

CHANGELOG.rst
kinto_signer/listeners.py
tests/config/signer.ini
tests/functional.py
tests/test_plugin_setup.py

 Fix crash on collection delete (fixes #248) 

---

CHANGELOG.rst
setup.py

Ethan, I realize I didn't wait for your formal approval on #249  (I don't worry too much since the fix was trivial and the PR added functional tests...)
I can still change stuff here before releasing if you want

Preparing release 3.2.3

---

kinto_signer/updater.py
tests/test_updater.py

Fix CloudFront invalidation request with multiple paths (fixes #253)

---

dev-requirements.txt
kinto_signer/utils.py
tests/test_signer_attachments.py

Prevent kinto-attachment to raise errors when attachments are updated (fixes #256)

---

CHANGELOG.rst
README.rst
kinto_signer/listeners.py
kinto_signer/updater.py
kinto_signer/utils.py
tests/functional.py
tests/test_signoff_flow.py
tests/test_updater.py

Refresh signature (fixes #245)

---

CHANGELOG.rst
kinto_signer/listeners.py
tests/functional.py
tests/test_signoff_flow.py

Allow refresh of signature even if the collection was never signed (fixes #267)

---

CHANGELOG.rst
kinto_signer/listeners.py
tests/test_events.py

Prevent events to be sent if status is not changed (#268)

---

CHANGELOG.rst

Enable Wheel distribution (fixes #271)

---

CHANGELOG.rst
kinto_signer/canonicaljson.py
tests/test_canonicaljson.py

...that was the missing test you were talking about!
```
E           AssertionError: assert '0e+0' == '0'
E             - 0e+0
E             + 0
```

Fix serialization of 0

---

tests/config/signer.ini

As noted in https://github.com/mozilla-services/cloudops-deployment/pull/2726

Remove redundant config

---

setup.cfg

This should make it more likely that wheels are produced for this
package.

Add a setup.cfg

---

CHANGELOG.rst
kinto_signer/updater.py
tests/test_updater.py

Do not invalidate CloudFront on signature refresh (fixes #430)

---

kinto_signer/listeners.py
tests/test_events.py
tests/test_plugin_setup.py
tests/test_signoff_flow.py

Raise if signing fail (fixes #591)

---

CHANGELOG.rst
kinto_signer/__init__.py
kinto_signer/events.py
kinto_signer/listeners.py
kinto_signer/updater.py
tests/test_signoff_flow.py

Add StatsD counter for number of changes approved (fixes #606)

---

CHANGELOG.rst
kinto_signer/__init__.py
kinto_signer/updater.py
kinto_signer/utils.py

Based on #618 
Please change base to master before reviewing/merging.

Move to f-strings.

---

CHANGELOG.rst
kinto_signer/__init__.py
kinto_signer/listeners.py
tests/test_signoff_flow.py

Prevent preview and destination collections to be deleted (fixes #641)

---

README.rst
kinto_signer/events.py
kinto_signer/listeners.py
kinto_signer/updater.py
kinto_signer/utils.py
tests/functional.py
tests/test_events.py
tests/test_signoff_flow.py

 Rollback changes (fixes #260)

---

kinto_signer/listeners.py
requirements.txt
tests/test_signoff_flow.py

fixes #684
This patch took me a lot more time than expected... I would gladly take some time to explain. And it's probable that there's a simpler approach, but I couldn't just find it.

Fix collection deletion safety check (fixes #684)

---

kinto_signer/listeners.py
tests/functional.py
tests/test_events.py
tests/test_signoff_flow.py

fixes #683
See also:
* https://github.com/Kinto/kinto-signer/pull/269
* https://github.com/Kinto/kinto-signer/pull/227

 Set status of new collections to signed (fixes #683) 

---

CHANGELOG.rst
kinto_signer/signer/__init__.py
kinto_signer/signer/autograph.py
tests/test_plugin_setup.py
tests/test_signer.py
tests/test_signer_attachments.py
tests/test_signoff_flow.py

Log Autograph requests references (#687)

---

CHANGELOG.rst
kinto_signer/listeners.py
tests/test_signoff_flow.py

Fix crash in collection deletion safety check (fixes #709)

---

kinto_signer/updater.py
kinto_signer/utils.py
tests/test_events.py
tests/test_updater.py

Fix records dropped since #780 (fixes #816)

---

kinto_signer/listeners.py
tests/test_signoff_flow.py

Before this PR, when `to_review_enabled` was false and a preview collection defined in settings, the code would not update the preview collection on signoff.  And our consistency check in Poucave, that verifies that source == preview == prod when status is signed would fail.
With this PR, we can have a collection with review disabled and the preview collection will still be updated

Fix behaviour with preview collection when review is disabled

---

tests/test_events.py

Resource events on resign (fixes #261)

---

CHANGELOG.rst
kinto_signer/updater.py
tests/test_signoff_flow.py

Copy schema field to destination metadata (fixes #518)
