Kinto/kinto-signer

kinto_signer/tests/functional.py
kinto_signer/tests/test_updater.py
kinto_signer/updater.py

Deleted records are now replicated to the destination collection when a new
signature is generated.
Fixes #25.
r? @leplatrem @Natim

Handle deletions on the source.

---

kinto_signer/tests/config/autograph.yaml

The `x5u` attribute will be exposed in collection `signature` metadata.
@mozmark r?

Add x5u to Autograph config

---

kinto_signer/tests/test_updater.py
kinto_signer/updater.py

When reading the code, I got confused by what was the "local" collection, the "destination" collection and sometimes the "remote" collection.
I propose that we use "source" and "destination" everywhere to avoid confusion, and get rid of "local" and "remote"

rename "local" to "source" and "remote" to "destination" everywhere

---

kinto_signer/tests/test_updater.py
kinto_signer/updater.py

The exception is raised here: https://github.com/Kinto/kinto-signer/blob/master/kinto_signer/updater.py#L147
I don't know yet how this can of raise can happen but we should catch the exception.

kinto-signer raises an exception when trying to delete already deleted records

---

demo/index.html
demo/index.js

I followed [Franciskus advice](https://github.com/Kinto/kinto-signer/issues/79#issuecomment-219637787) and added a `textarea` whose value is the current x5u chain.
It should do it, at least as a first step.
@Natim r?

Use a text for the certificate chain (fixes #79)

---

demo/index.html

npmjs CDN doesn't serve http file anymore.
r? @leplatrem

Fix http loading.

---

CHANGELOG.rst
kinto_signer/__init__.py
kinto_signer/tests/functional.py
kinto_signer/tests/test_events.py
kinto_signer/tests/test_updater.py
kinto_signer/updater.py
requirements.txt
setup.py

This is major rewrite of the updater in order to trigger `ResourceChanged` events when the destination collection/records are updated (on signing).
The challenges are:
* Leverage the resource code that builds and sends events
* Trigger a `ResourceChanged` from a `ResourceChanged` may not be natural :)
* Rewrite the tests since they rely on mocks and are broken
I chose to go with invoque_subrequest() instead of the kind of [awful code](https://github.com/Kinto/kinto/blob/3.3.1/kinto/plugins/default_bucket/__init__.py#L67-L113) we currently have in the default bucket plugin.
I find the result convincing and promising (most events tests pass), but I need feedback :)
@almet @Natim f?

Trigger resource events on destination collection/records

---

scripts/validate_signature.py

Needs https://github.com/Kinto/kinto-http.py/pull/80 to run.

When using the ETag the collection signature is incorrect.

---

CHANGELOG.rst
kinto_signer/listeners.py
tests/test_signoff_flow.py

Use a dedicated errno in 403 responses when operation is forbidden (Fixes #135)

---

kinto_signer/listeners.py

Did not figure out how to test properly, but this is a bug.
**Notes**: the line `updater.update_source_editor(event.request)` is supposed to trigger an event, but it gets grouped with the current event and an impacted record is added to the list. This causes the loop to be executed twice, possibly executing `updater.sign_and_update_destination()` twice on the preview collection

Prevent recursivity for to-review

---

scripts/e2e.py

This is a quick hack to try to get kinto-dist to build.
canonical_json does a `copy.deepcopy` on its argument, although it isn't exactly clear why, since it never modifies it. Either way, though, we still ought to make sure that it handles sequences (i.e. iterators more robustly).

e2e: get_records now returns an iterator

---

CHANGELOG.rst
README.rst
kinto_signer/__init__.py
tests/test_events.py

We used to send the events on `AfterResourceChanged`. The `ResourceChanged` events were thus emitted out of the request transaction. Introducing inconsistencies in the way subscribers had to manage the manual commit when performing database changes.

Send kinto-signer events before commit

---

.travis.yml
Makefile
README.rst
kinto_signer/signer/__init__.py
kinto_signer/signer/autograph.py
kinto_signer/signer/local_ecdsa.py
tests/config/autograph.yaml
tests/test_plugin_setup.py
tests/test_signer.py

This is a work in progress, do not merge yet.
It is tied to https://github.com/mozilla-services/autograph/pull/46
The `content-signature` is being moved into the `signature` field and need to be parse before being decoded and verified. It's a minor change, and will also ensure that the content signature we're giving the users is the one we're verifying.

Update to autograph v2 response format

---

CHANGELOG.rst
kinto_signer/__init__.py

Requires https://github.com/mozilla-services/cloudops-deployment/pull/1623 to be merged and deployed before upgrading prod to this version.

Drop legacy underscore prefix in settings

---

CHANGELOG.rst
README.rst
kinto_signer/__init__.py
tests/test_plugin_setup.py

Fixes #210
Based on #208 
> Note: this is backward compatible with Kinto-Admin since we expand the placeholders for every collection in the capabilities

Allow placeholders in review settings (fixes #210)

---

kinto_signer/__init__.py
kinto_signer/listeners.py
tests/test_signoff_flow.py

Ref #215 
Discovered while hacking on #218: if a setting was overriden for a specific collection with the rest configured as per-bucket, it was **not** taken into account.
I'm not super happy about the fix (going back to settings in `pick_resource_and_signer()`), but I can't see any better way with the current code. See #220

Fix overriding of per-bucket settings (Ref #215)

---

CHANGELOG.rst
README.rst
kinto_signer/utils.py
tests/config/signer.ini
tests/test_events.py
tests/test_plugin_setup.py
tests/test_signoff_flow.py
tests/test_utils.py

Strip spaces from resources (fixes #148)

---

README.rst
requirements.txt
setup.py

This let me run kinto-signer successfully in a Python 3.6 venv.

Drop support for Python 3.4

---

CHANGELOG.rst
kinto_signer/listeners.py
tests/test_signoff_flow.py

Give write permission to reviewers/editors groups on newly created collections (fixes #237)

---

CHANGELOG.rst
kinto_signer/updater.py
tests/test_signoff_flow.py

As recommended by @glasserc  in #244 
```
>>> Date.parse('2018-04-25T11:22:43.967335')
1524648163967
>>> Date.parse('2018-04-25T11:22:43.967335+00:00')
1524655363967
```

Make sure the dates in tracking fields are given on the UTC timezone

---

CHANGELOG.rst
kinto_signer/__init__.py
kinto_signer/listeners.py
tests/test_plugin_setup.py

Fixes #114 
I realized that QA would need to create / delete / and potentially recreate source collections.
Instead of deleting the preview/destination collections, which would break clients, I delete the records with tombstones and resign as empty.

Cleanup preview and destination when source collection is deleted (fixes #114)

---

dev-requirements.txt

pytest-cover was deprecated some time ago.
See also https://github.com/Kinto/kinto/pull/1543.

Move from pytest-cover to pytest-cov

---

kinto_signer/listeners.py
kinto_signer/updater.py
kinto_signer/utils.py
requirements.txt
setup.py

It seems that this entire send_resource_events function only exists as
a workaround for the problem that is being fixed by
Kinto/kinto#1671.
This PR won't work until Kinto/kinto#1671 lands and is released, but (assuming the tests pass), does this seem OK to you, @leplatrem ?
Fixes #263. Note that we leave the explicit manipulation of `kinto_signer.events` in place -- this is meant to let us trigger events after resource events but before the transaction commits.

Update now that events can trigger events

---

CHANGELOG.rst
scripts/e2e.py

Rewrite e2e to use .get_records_timestamp() (#258)

---

kinto_signer/listeners.py
kinto_signer/updater.py
setup.py
tests/test_events.py
tests/test_plugin_setup.py
tests/test_signoff_flow.py

The more I try to investigate the more I get lost with what seems to happen...
Like, I added this print after the delete in the tests:
```py
dest_ts = int(self.app.head(self.destination_collection + "/records", headers=self.headers).headers["ETag"][1:-1])
ts = [r["last_modified"] for r in self.app.get(self.source_collection + "/records?_since=0", headers=self.headers).json["data"]]
print("dest col ts=", dest_ts, "source records=", ts, [t > dest_ts for t in ts])
```
And here's what I obtain:
```
dest col ts= 1547747840898 source records= [1547744241061, 1547744241039] [False, False]
```
How come the timestamps of the deleted tombstones are not superior to the destination timestamp if the delete happens after it was updated... ?
I'll leave it for a while..

Fix copy of deleted records (ref #283)

---

CHANGELOG.rst
kinto_signer/__init__.py
tests/test_plugin_setup.py

@leplatrem discovered this by accident today. It's a security bug that was introduced by #280. So far we're only affected on per-collection settings, but in fact a related bug seems to be present for per-bucket settings.

kinto-signer exposes signing settings

---

kinto_signer/listeners.py

This passes all the same tests but is simpler:
- Extract signer_impacts_resource utility functions. It might be worth
defining two versions of this: a bucket-wide one and a
bucket-specific one.
- Don't attempt to vectorize this check in any way. We're already in a
loop so we can simplify by just considering the given bid/cid and
not trying to build/update a map.
- Excessive comments explaining what's going on at each step.
- Articulate the invariants this approach relies on. These invariants
are implied but not actually enforced by the parse_resources
function, so be defensive.

Rewrite prevent_collection_delete

---

CHANGELOG.rst
kinto_signer/updater.py
tests/functional.py
tests/test_updater.py

Bump timestamps when pushing in destination collection (fixes #779)

---

kinto_signer/updater.py
tests/test_signoff_flow.py
tests/test_updater.py

Fixes #832
When listing the source and destination records sets, we would include tombstones. This is not necessary anymore since we do a plain comparison of the two sets (since #817).
There is still a failing test about reported startsd value, that I will look into as soon as I can

Do not recreate tombstones on rollback (fixes #832)

---

kinto_signer/updater.py
tests/test_events.py

If rollback does not send events, then users are confused with information shown in the Admin UI. 
This should at least help have consistent info in history.
--> https://github.com/Kinto/kinto-admin/issues/1174#issuecomment-577728891

Send resource events on rollback 

---

CHANGELOG.rst
README.rst
kinto_signer/__init__.py
kinto_signer/listeners.py
tests/test_plugin_setup.py

Using a script I could verify that only 3 records among all collections in the Remote Settings server use floats.
```
main/cfr 'content.text.addon.id.icon.title.users.author.rating' field contains float value 4.5 (tip: use string)
main/cfr 'content.text.addon.id.icon.title.users.author.rating' field contains float value 4.2 (tip: use string)
main/cfr 'content.text.addon.id.icon.title.users.author.rating' field contains float value 4.7 (tip: use string)
main-preview/cfr 'content.text.addon.id.icon.title.users.author.rating' field contains float value 4.5 (tip: use string)
main-preview/cfr 'content.text.addon.id.icon.title.users.author.rating' field contains float value 4.2 (tip: use string)
main-preview/cfr 'content.text.addon.id.icon.title.users.author.rating' field contains float value …
```

Records shouldn't contain float values anymore

---

CHANGELOG.rst
kinto_signer/listeners.py
tests/test_events.py
tests/test_plugin_setup.py
tests/test_signoff_flow.py

This removes the old way to refresh signatures, and improves the overall API consistency.

Remove ability to refresh signature with to-sign status

---

CHANGELOG.rst
kinto_signer/updater.py
tests/test_signoff_flow.py

See https://github.com/Kinto/kinto-admin/issues/1918

Reset the editor/reviewer comments when not specified

---

scripts/validate_signature.py

We are updating the Remote Settings stage domain names to make them more consistent. See https://bugzilla.mozilla.org/show_bug.cgi?id=1594573 for details.

Update Remote Settings stage domain.
